global_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  update_frequency: 1.0
  publish_frequency: 0.5
  transform_tolerance: 0.5
  static_map: true

  width: 10.0
  height: 10.0
  resolution: 0.05

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: "/map"
    first_map_only: false
    subscribe_to_updates: true

  inflation_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 10.0

